export type ProjectItem = {
  id: number,
  title: string,
  slug: string,
  slug_ar: string,
  slug_en: string,
  description: string,
  location: string,
  price: number,
  percentage_amount: number,
  price_list: number[],
  payment_type: string,
  dropdown: { options: string }[] | null,
  itemSlider: string[],
  single_price: number | null,
  additionalInfo: {bold_description: string | null, normal_description: string | null, project_story: string | null} | null,
  image: string,
  image_mobile: string,
  image_tablet: string,
  type_id: number,
  type: 'projects' | 'crowdfunding' | 'organization',
  category: {
    id: number,
    title: string,
    slug: string,
    slug_ar: string,
    slug_en: string,
    image: string,
    description: string,
    is_all_option: boolean,
    hero_title: string,
    hero_description: string,
    hero_image: string
  }
}