uploads = []
outputs = []

[[generated]]
id = "gCg8_O9JKHoSHthxfqdWM"
uri = "file://tog4dev-backend/storage/app/public/about/items/founder-1.png"
type = "image"
title = "founder one portrait"

[[generated]]
id = "DxwraXdHKuxDh0ugpqH6T"
uri = "file://tog4dev-backend/storage/app/public/about/items/founder-2.png"
type = "image"
title = "founder two portrait"

[[generated]]
id = "oKdHp0X8Tznw8-3jXhM_5"
uri = "file://tog4dev-backend/storage/app/public/about/items/founder-3.png"
type = "image"
title = "founder three portrait"

[[generated]]
id = "i8uK97JtLMaANF_cQ1azI"
uri = "file://tog4dev-backend/storage/app/public/about/sections/journey-team.png"
type = "image"
title = "journey team photo"

[[generated]]
id = "Bs6rgwRvJ-eAPo9mpVD7O"
uri = "file://tog4dev-backend/storage/app/public/about/partners/partner-1.png"
type = "image"
title = "partner logo one"

[[generated]]
id = "J-CmyPur9fOlpIvJq3V-J"
uri = "file://tog4dev-backend/storage/app/public/about/partners/partner-2.png"
type = "image"
title = "partner logo two"

[[generated]]
id = "1Ev-dHvO7m1oANFWT20Vw"
uri = "file://tog4dev-backend/storage/app/public/about/partners/partner-3.png"
type = "image"
title = "partner logo three"

[[generated]]
id = "knmdQigHrkbNorNJ4Lt23"
uri = "file://tog4dev-backend/storage/app/public/about/partners/partner-4.png"
type = "image"
title = "partner logo four"

[[generated]]
id = "3D3X9rbGf1FfImczthzqI"
uri = "file://tog4dev-backend/storage/app/public/about/partners/partner-5.png"
type = "image"
title = "partner logo five"

[[generated]]
id = "SqJEv4KIepkaCG46ZbApd"
uri = "file://tog4dev-backend/storage/app/public/about/partners/partner-6.png"
type = "image"
title = "partner logo six"
